import Head from "next/head"
import Link from "next/link"
import styles from "client/styles/Home.module.css"

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{" "}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <div className={styles.grid}>
                    <Link href="/movie">
                        <a className={styles.card}>
                            <h2>Movie &rarr;</h2>
                            <p>Lots of movies!</p>
                        </a>
                    </Link>

                    <Link href="/movie">
                        <a className={styles.card}>
                            <h2>Movie &rarr;</h2>
                            <p>Lots of movies!</p>
                        </a>
                    </Link>
                </div>
            </main>
        </div>
    )
}
